FROM node:18

# Install dependencies
RUN apt-get update && apt-get install -y \
  xvfb \
  libgtk-3-0 \
  libx11-xcb1 \
  libnss3 \
  libgconf-2-4 \
  libasound2

# Set up working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copys the rest of the project files
COPY . .

# Run the build script
CMD ["xvfb-run", "npm", "run", "build", "run poststart"]
