title: HtWebz Assistant
description: A short description of your site
baseurl: ""
url: "https://GMM-rgb.github.io/machine_learning/public/AI_HtWebz_Assistant_Version%200.4.html"
source: .
destination: ./_site

sass:
  style: compressed
exclude:
  - assets/css/style.scss
