title: HtWebz Assistant
description: A short description of your site
baseurl: ""
url: "https://GMM-rgb.github.io/machine_learning/"
source: .
destination: ./_site

sass:
  style: compressed
exclude:
  - assets/css/style.scss
