name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["Backup-1"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Sync submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install dependencies
        run: npm install

      - name: Audit fix
        run: npm audit fix & npm audit fix --force

      - name: Log build directory
        run: ls -la public/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./public"
          destination: "./public/_site"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public/_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    with: npm run poststart
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4/
        with:
          node-version: "18"

    #Finalize:
    # enviorment:
    #  name: Fabricate Site With Node.js

    # runs-on: ubuntu-latest

    #- name: Build Site
    # run: npm run poststart
